// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeslaRentingApp;

#nullable disable

namespace TeslaRentingApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeslaRentingApp.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Loc_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Loc_Name");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Palma Airport"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Palma City Center"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Alcudia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Manacor"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Colònia de Sant Jordi"
                        });
                });

            modelBuilder.Entity("TeslaRentingApp.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Mod_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("Mod_Capacity");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mod_Image");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mod_Name");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("money")
                        .HasColumnName("Mod_PricePerDay");

                    b.Property<int>("Range")
                        .HasColumnType("int")
                        .HasColumnName("Mod_Range");

                    b.Property<int>("Seats")
                        .HasColumnType("int")
                        .HasColumnName("Mod_Seats");

                    b.HasKey("Id");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 28,
                            ImageName = "model-s-plaid.png",
                            Name = "Model S Plaid",
                            PricePerDay = 49.18m,
                            Range = 396,
                            Seats = 5
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 28,
                            ImageName = "model-s.png",
                            Name = "Model S",
                            PricePerDay = 42.18m,
                            Range = 405,
                            Seats = 5
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 23,
                            ImageName = "model-3-performance.png",
                            Name = "Model 3 Performance",
                            PricePerDay = 27.55m,
                            Range = 315,
                            Seats = 5
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 23,
                            ImageName = "model-3-long.png",
                            Name = "Model 3 Long Range",
                            PricePerDay = 24.32m,
                            Range = 333,
                            Seats = 5
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 23,
                            ImageName = "model-3-rear.png",
                            Name = "Model 3 Rear-Wheel Drive",
                            PricePerDay = 22.18m,
                            Range = 272,
                            Seats = 5
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 88,
                            ImageName = "model-x-plaid.png",
                            Name = "Model X Plaid",
                            PricePerDay = 42.31m,
                            Range = 333,
                            Seats = 6
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 88,
                            ImageName = "model-x.png",
                            Name = "Model X",
                            PricePerDay = 38.78m,
                            Range = 348,
                            Seats = 7
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 76,
                            ImageName = "model-y-performance.png",
                            Name = "Model Y Performance",
                            PricePerDay = 29.99m,
                            Range = 303,
                            Seats = 5
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 76,
                            ImageName = "model-y-long.png",
                            Name = "Model Y Long Range",
                            PricePerDay = 26.74m,
                            Range = 330,
                            Seats = 7
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 76,
                            ImageName = "model-y-rear.png",
                            Name = "Model Y Rear-Wheel Drive",
                            PricePerDay = 23.25m,
                            Range = 260,
                            Seats = 5
                        });
                });

            modelBuilder.Entity("TeslaRentingApp.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Res_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int")
                        .HasColumnName("Res_CarId");

                    b.Property<decimal>("Cost")
                        .HasColumnType("money")
                        .HasColumnName("Res_Cost");

                    b.Property<int>("DateEnd")
                        .HasColumnType("int")
                        .HasColumnName("Res_DateEnd");

                    b.Property<int>("DateStart")
                        .HasColumnType("int")
                        .HasColumnName("Res_DateStart");

                    b.Property<int>("LocIdEnd")
                        .HasColumnType("int")
                        .HasColumnName("Res_LocIdEnd");

                    b.Property<int>("LocIdStart")
                        .HasColumnType("int")
                        .HasColumnName("Res_LocIdStart");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("Res_UserId");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("TeslaRentingApp.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Usr_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Usr_Email");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Usr_FirstName");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Usr_LastName");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Usr_Login");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Usr_Password");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Usr_Phone");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Usr_Salt");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
